### ISSUE TITLE
Dealing with 0-based and 1-based index offset 

### ISSUE THREAD

**Issue by Etiene** [paulcuth/starlight#15]
Currently, if I run in Lua a javascript function that returns an array, it will return a 0-based table. So, for example, when I do this, I won't be able to iterate through the result like I'd normally do in Lua and I'm forced to use a numeric for:

    local title_divs = window.document:getElementsByClassName("post-title")

Should this result in 1-based tables?

**Comment by paulcuth** [comment]
I guess it should, yes. I'll take a look...
