### ISSUE TITLE
Bug on function call on expression

### ISSUE THREAD

**Issue by Etiene** [paulcuth/starlight#17]
Hello, I found an odd behaviour! :)

```
local function test()
	return true
end

print(test()) -- true
print(test() and true) -- true
print(true and test()) -- userdata 
```

**Comment by paulcuth** [comment]
Hi Etiene, Sorry for the delay on this. 

I can't repeat it; I think it was fixed in https://github.com/paulcuth/starlight/commit/ad546a362f1662455f168525004c602617b96b96. I'm going to close this, please feel free to reopen if you think it's still an issue.

PC.

**Comment by Etiene** [comment]
Ok! I'll give it another try with the most recent version as soon as I have the time and let you know! thanks
