### ISSUE TITLE
Support for NodeJS

### ISSUE THREAD

**Issue by darmie** [paulcuth/starlight#18]
Hi, can starlight parser work with NodeJS AMD? 

What I mean is, can I "require"  starlight in my NodeJS project? 

I am trying to use Starlight with Famous Engine 
  
https://github.com/Famous/engine

**Comment by paulcuth** [comment]
This isn't something that I've done before, but it looks like it should be possible to require CommonJS modules with little effort: http://requirejs.org/docs/node.html#2
I'm going to close this issue, please feel free to reopen if you can't find an appropriate solution.
