### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by vadi2** [paulcuth/starlight#34]
I hacked an example together, but it's giving me an error. Same code runs in lua.vm.js, though. This is the gist: https://gist.github.com/vadi2/df131203a5601160cd13eda8062fb3f8

Chrome says:

```
runner-3.35.12.min.js:1 [BABEL] Note: The code generator has deoptimised the styling of "unknown" as it exceeds the max of "100KB".e.(anonymous function) @ runner-3.35.12.min.js:1t.normalizeOptions @ browser.min.js:3t @ browser.min.js:3t.exports @ browser.min.js:4t.generate @ browser.min.js:5t.transform @ browser.min.js:4(anonymous function) @ browser.min.js:6t.wrap @ browser.min.js:4e.transform @ browser.min.js:6f @ starlight.js:4g @ starlight.js:4(anonymous function) @ starlight.js:4
VM1817:4 Uncaught (in promise) SyntaxError: Unexpected identifier(…)
```

Firefox says:

```
[BABEL] Note: The code generator has deoptimised the styling of "unknown" as it exceeds the max of "100KB". runner-3.35.12.min.js:1:9080

SyntaxError: missing ; before statement starlight.js:1:21
```

**Comment by vadi2** [comment]
Firefox also mentions this in the console:

```
true
"Only one iterator is assumed. Need to implement more!"
```

**Comment by paulcuth** [comment]
This is now fixed on `master` and, as your page is pointing to the now updated file on my server, it should work straight away. However, you should be aware that Lua's `io` standard library is not implemented in Starlight and therefore the script now fails with `attempt to index a nil value` when attempting to use `io.read()`.

Thank you and please feel free to share any further issues you find.

**Comment by vadi2** [comment]
Great, thanks for the quick turnaround.

**Comment by paulcuth** [comment]
I forgot to mention that you're also missing the block of code from the demo that that initialises the `ui` variable... https://github.com/paulcuth/starlight-examples/blob/master/grunt-modules/src/app.lua#L5-L9

Regards.
