### ISSUE TITLE
v0.4.0: demo fail: browser-lib: Cannot read property 'globalScope' of undefined

### ISSUE THREAD

**Issue by d9k** [paulcuth/starlight#45]
`grunt browser-lib`, then opening `dist/browser-lib/index.html`

Error at console:

```
Uncaught (in promise) TypeError: Cannot read property 'globalScope' of undefined
    at eval (eval at h (starlight.js:4), <anonymous>:8:18)
    at eval (eval at h (starlight.js:4), <anonymous>:65:4)
    at starlight.js:4
```

`http://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.34/browser.min.js`
`Google Chrome 56.0.2924.87 (64-bit)`

**Comment by d9k** [comment]
@paulcuth

**Comment by paulcuth** [comment]
Hi, sorry for the delay in responding. Is this still an issue with the current `master` branch? I can't recreate it.

**Comment by d9k** [comment]
@paulcuth, thx for checking an issue!
works for me now at `master` branch (`v. 0.3.3`)! cool!

**Comment by d9k** [comment]
@paulcuth btw, at `beta` branch `dist/browser-lib/index.html` scripts fails at `Hello` button press on page load

```
Uncaught (in promise) ReferenceError: $undefined is not defined
    at __star_tmp (eval at h (starlight.js:4), <anonymous>:4:21)
    at t (starlight.js:1)
    at e (starlight.js:1)
    at eval (eval at h (starlight.js:4), <anonymous>:6:18)
    at starlight.js:4
    at <anonymous>
```
