### ISSUE TITLE
How to send json object ?

### ISSUE THREAD

**Issue by CriztianiX** [paulcuth/starlight#48]
Is this posible ?

```lua
local input = window:jq('.autocomplete')
input:autocomplete({
    serviceUrl = '/ajax/suggest/banks',
    paramName = 'q',
    onSelect = function(suggestion)
        print(suggestion)
      --$(this).val(suggestion.data);
    end
})
```

I get: 

> 
> VM935:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
>     at Function.parse [as parseJSON] (<anonymous>)
>     at Object.d [as transformResult] (jquery.autocomplete.min.js:8)
>     at Object.<anonymous> (jquery.autocomplete.min.js:8)
>     at i (jquery.min.js:2)
>     at Object.fireWith [as resolveWith] (jquery.min.js:2)
>     at A (jquery.min.js:4)
>     at XMLHttpRequest.<anonymous> (jquery.min.js:4)

Here the js:
https://pastebin.com/cFZw2PMr

**Comment by paulcuth** [comment]
Hi, 

Apologies for the delay. Yes, this is possible; see example code here:
http://jsbin.com/xequfupuzu/edit?html,console,output

Let me know if you need any more help.
